name: PROD-to-DEV

on:
  workflow_dispatch:

permissions: read-all

jobs:
  prod_to_dev:
    name: Rebase from production to development
    environment:
      name: Development
      url: https://dev-sws2apps.herokuapp.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout for rebase preparation
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          ref: alpha
          token: ${{ secrets.GH_TOKEN }}

      - name: Do git rebase
        run: |
          git fetch --all
          git checkout alpha
          git rebase --onto origin/main alpha
          git push -f origin alpha

      - name: Deploy API to Heroku
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: dev-sws2apps
          heroku_email: ${{secrets.HEROKU_EMAIL}}
